adminUser:
  password: vault:central/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jx-bot@gmx.ch
  token: vault:central/pipelineUser:token
  username: ccojocar-bot
prow:
  hmacToken: vault:central/prow:hmacToken
